- README.md
Fixes https://github.com/drduh/YubiKey-Guide/issues/11
> Adds explanation of ssh-add -L option

- README.md
Fixes https://github.com/drduh/YubiKey-Guide/issues/7
> Add key checking

- README.md
Fixes https://github.com/drduh/YubiKey-Guide/issues/5
> Add instructions for installing gnupg-curl

- README.md
> Make hkt respect custom $GNUPGHOME

- README.md
gpg 2.1/2.2 brings a few changes; also include macOS config.
> Updates for gpg 2.2.1, and also macOS support

- README.md
the "export" command was missing ...
> fix exporting KEYID

- README.md
9.5.0 is not available anymore so I figured an update would be in order.
> Update live Debian version to 9.6.0

- README.md
Was looking at how to access on remote machines, is a standard ssh workflow, but might be useful to have it here too.
>  Agent Forwarding 

- README.md
This commit applies a few editorial cleanups to the document:
1. `keytocard` operations now contained emphasized warnings to convey
that these operations are destructive.  I unknowingly made this
mistake a few years ago and only learned of it recently.  For that
reason, we should go out of our way on user's behalf with due
diligence warnings.
2. `$KEYID` was not uniformly used throughout the document in various
command line input literals.  This is now fixed.
3. `YubiKey` was often represented as `Yubikey` and other
inconsistent forms throughout the document.  This is now fixed,
except in cases of URL, command output, etc.
> Emphasize keytocard danger and fix inconsistency.

- README.md
link to Yubico's page that offers a selection of browsers.
> no need to support the monopoly

- README.md
The correct syntax is `date +FORMAT`.
> Correct date invocation

- README.md
Source appears to have changed some dashes with spaces.
> Fix link to supply chain attacks

- README.md
Hi,
Thank you for your excellent guide on how to use the Yubikey. After I used your guide, I got [mailvelope](https://www.mailvelope.com/en) to work and thought it would be useful to share the instructions. 
While it's not complete (I don't have a Linux machine to test the instructions right now) I hope you can consider including it to help others.
> Describe how to enable mailvelope on MacOS

- README.md
Add instructions for how to sign your new key with and old key and how to add multiple email addresses to your key.
I am a bit concerned that these have landed in the wrong place in the document.
> Extra actions

- README.md
Added note mentioning depending on users accepted level of risk. Running the OS in a VM is a viable option
> Update VM option

- README.md
> Add --keyserver flag pointing to Debian keyserver

- README.md
> Mention yubikey-touch-detector

- README.md
NixOS lets you set up a bootable USB with the necessary software pre-installed.
I just tested these steps on a spare laptop.
> Add instructions for NixOS

- README.md
As discussed in issue #164, the current section on Rotating Keys presents two alternatives: replacing the existing keys with a newly generated key or extending the validity of existing keys by changing
their expiration.  However, it only provides instructions for the first approach.  This commit adds instructions for renewing sub-keys.
I am far from an expert, and am submitting this change mostly in hopes that it will provide documentation for the next time I need to renew my sub-keys.  I would welcome any changes or clarifications others would care to offer.
> Add steps for renewing (not rotating) sub-keys

- README.md
As proposed, I added my ideas about storing the whole workspace for late reuse as well as just aborting the keytocard action when creating multiple Yubikeys with the same key.
> Added some additonal text describing alternatives that may be used

- README.md
gpg-connect-agent uses `-r/--run` not `-R`
> Fix reset command

- README.md
The provided PowerShell command will make it a bit easier to find the device name and copy it.
> Add PowerShell command to get YubiKey name

- README.md
proposed change according to Issue#215
> Additions to "Required Software"

- README.md
> Quick VMware Name Correction

- README.md
openpgp set-pin-retries is moved to openpgp access set-retries
> Update ykman openpgp command

- README.md
> add polkit rule troubleshooting tip

- README.md
Huge thanks to @Paraphraser and @mattrobineau for [this thread](https://github.com/drduh/YubiKey-Guide/issues/337), without which I definitely would not have been able to figure this out! I figured since I was at least the second person to try to figure this out, it was worth writing up.
I went through this last night, so I'm nearly certain I got it right, but please let me know if anyone has any feedback. I'll leave some inline comments on parts that I'm less confident in!
> Add instructions for adding a new identity

- README.md
Issue #382 suggests adding a section explaining how to use the same YubiKey on multiple hosts.
Since extended to explain how to set up card URL field to fetch public key from key-server.
Fixes: #382
Fixes: #381
> 2023-06-28 Add section on setting up multiple hosts

- README.md
Fixes https://github.com/drduh/YubiKey-Guide/issues/370.
> Fix NixOS LiveCD image build

- README.md
> Address restriction on subkey

- README.md
date +F => 'F'
Thanks for the guide and happy to see it is still developing!
> Fix typo in date command

- README.md
- passphrase.csv
- passphrase.html
Fields for date, 16-digit key ID and 8-digit serial number instead of the unused reset PIN template.
> Improved passphrase templates

- README.md
> Corrected small typo in README.md

- README.md
Hi, thank you for creating the Nix live image configuration. It's very handy to be able to configure a full system so easily. Since I started tweaking the system a bit, I found it useful to document a useful QEMU invocation. I am opening a pull request here with my changes.
I've also fixed some trailing white space.
> Add instructions how to run NixOS YubiKey live image with QEMU

- README.md
> use printf, export keyid, fix link

- passphrase.html
- consolidate stylesheet
- alternate row background
- add verbose instructions
- reduce filesize by 8x
> refactor passphrase template html

- scripts/generate.sh
script key generation steps for testing and possible use with #495
> script key generation

- SECENV.md
> [!NOTE]
> Implements #499.
**Purpose.** This document describes a process for creating a secure environment using Alpine Linux: a lightweight and secure distribution of Linux capable of supporting newer versions of GPG with smart card support on very modest hardware such as the ARM-based Raspberry Pi 1 Model B (32-bit). This document also demonstrates the highly portable characteristics of Alpine Package Keeper (APK) to provide for ease of package installation and use in air-gapped environments.
**Tags.** Tails OS, Alpine Linux, GnuPG, Raspberry Pi.
**Disclaimer.** The procedures outlined in this document are provided as best effort measures for creating a safer working environment for managing GPG keys; and are not intended to eliminate every possible threat scenario including, but not …
> Creating a Secure Environment for GPG in Alpine Linux
