README.md

The public key must be written on a file.

Export public key to file

---

README.md

Fix to use the yubikey on Tails. Without that you won't be able to change operation mode with ykpersonalize.
https://github.com/freedomofpress/securedrop/issues/1035

yubikey tails fix

---

README.md

https://rnorth.org/8/gpg-and-ssh-with-yubikey-for-mac is https://rnorth.org/gpg-and-ssh-with-yubikey-for-mac now.

Change rnorth link

---

README.md

If you try `git fetch upstream` on github and you have ssh-agent running, you'll get this error.

Add an extra error condition

---

README.md

The signature was made using `0xBECFA3C1AE191D15`, and has to be used with the signing key, not the root key.
I can verify this with my own key -- using the keyid doesn't work:
```
~   echo "$(uname -a)" | gpg --armor --clearsign --default-key 0xB1A9D5A2A605F794
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512
Linux Puget-153699 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
-----BEGIN PGP SIGNATURE-----
iQIcBAEBCgAGBQJX5aWdAAoJECaAG7YBLqXZi1EP/3R4oOdkXqZXcskwzfjBXa68
oZeKxTB8i74tSPXp0SL26+ULOQ6GRJdIFod2MQtqfjeu6dyNEbIBF1pHWnyLx4Bn
p/+ROoOTiBSFEWPts++yYhmo0tS0cXPv6QPCYqj4mPkJe6u8wVp5hkoyujL/k9bs
cAZSbeyV/hggS0rFTN4/5AeUky4LJPrWYkAiln7D0PVQeZc6DFlDpeup1Az7hWV5
ImRglAfoacNq+0LWslnc51/4knFGC/k4RS/QAyfUNJG/yy/ZZs6FNc7FjyZkw87E …
```

Use signing subkey

---

README.md

Adds 
```
s2k-cipher-algo AES256
```
to the GPG configuration, per https://pthree.org/2015/11/19/your-gnupg-private-key/
> --s2k-cipher-algo name
> Use name as the cipher algorithm used to protect secret keys. The default cipher is CAST5. This cipher is also used for symmetric encryption with a passphrase if --personal-cipher-preferences and --cipher-algo is not given.
https://www.gnupg.org/documentation/manuals/gnupg-2.0/OpenPGP-Options.html#index-s2k_002dcipher_002dalgo

Use AES256 for private key password encryption

---

README.md

hkt does not support GnuPG 2.1 because it expects gpg pubring.
But the export can be done by gpg itself.

Replace hkt with gpg to fix unsupported GnuPG 2.1

---

README.md

Some colleagues were confused that a 4096 bit key does not fit on a YubiKey Neo, therefore I think it makes sense to emphasize the difference in the introduction, so that people don't have to repeat the first steps again.

emphasize 2048 bit as the correct key size for the YubiKey Neo

---

README.md

On all my archlinux computers, the ssh-agent does not work. I had to set SSH_AUTH_SOCK to `/run/user/$UID/gnupg/S.gpg-agent.ssh` to make it working.

Fix ssh-agent does not work on archlinux

---

README.md

Under section https://github.com/drduh/YubiKey-Guide#check-your-work there is an `apt-get` command to install `hopenpgp-tools`:
```
sudo apt-get install hopenpgp-tools
```
We should probably install this alongside the other tools for macOS using brew.
Otherwise, maybe we should update the section `#check-your-work` to give both a command for linux and macOS.

Install hopenpgp-tools with brew

---

README.md

Add optional section of guide in case user has `IdentitiesOnly yes` turned on in `ssh` client configurations (common if other privacy/security-focused ssh guides were followed), since keys loaded in `gpg-agent` will then not auto-enumerate.
In such a case, it is not necessarily obvious that `ssh -i [identity_file]` or `IdentityFile` configurations can be pointed at a saved copy of the *public key* instead (since there should be no access to the private key).

add explicit public key naming for IdentitiesOnly usage

---

README.md

Removing configuration paramaters no longer supported in GPG 2.X
Related to #28

Remove invalid config from gpg.conf

---

README.md

Minor change so that the signature will be downloaded, instead of the file itself

Fixing signature fetch command for ykpers

---

README.md

You'll often read that `gpg-agent` is a direct drop-in replacement for `ssh-agent`, and also occasionally that it _caches_ keys. Neither is strictly true, the additional information hopefully makes the nuances clear.

Add gpg-agent information.

---

README.md

`gpg SHA512SUMS.sign` would do the right thing only if the file actually contained a detached signature.
Use explicit and robust `gpg --verify SHA512SUMS.sign SHA512SUMS` instead.

Fix live image integrity check

---

README.md

Two commands mentioned later in the document won't work without two packages that don't come pre-installed with the Debian LiveCD:  dirmngr and secure-delete.

Add packages to apt-get list to fix gpg --recv and srm commands

---

README.md

As per [0], the --with-key-origin option is experimental.
0: https://www.gnupg.org/documentation/manuals/gnupg/GPG-Input-and-Output.html#index-with_002dkey_002dorigin

remove broken gpg option (debian 9.6)

---

README.md

I noticed there was an explanation for the warning of orange text, but not for red output that may show up if someone choosing to ignore this guides recommendation to not set an expiry for the red text. Putting this explicitly in the guide saves the reader the time of double-checking that this output has to do with the choice of not putting an expiring in place.

Add addition note about red hokey output

---

README.md

The Master key should only be capable of creating other subkeys, namely the `Certify` capability.

Master key should have Certify-capability only!

---

README.md

Section `Creating keys` ends with `Disable networking for the remainder of the setup.`.  All instructions that require a network should be before this sentence.
There seems to be no package `hopenpgp-tools` for RHEL.  I have no idea if one exists for OpenBSD.

Move install instructions for `hopenpgp-tools` to the top

---

README.md

On my system (Linux Mint) `gpgconf --list-dirs agent-ssh-socket` does return all dirs and not only the one for agent-ssh-socket hence `ssh-add -L` was failing. This is a hint for other people to troubleshoot this behaviour.

Add hint for setting up gpg-agent socket

---

README.md

It's not possible to use multiple YubiKeys containing the same GPG Keys with GnuPG as the serial number of the first used yubikey is stored by GnuPG. Here is a workaround I found, could be use-full for those you have this usage until GnuPG fixes this issue.

Using multiple YubiKey with same GPG keys

---

README.md

The syntax to change Yubikey touch configurations with ykman has changed. Updating this accordingly.
Relevant upstream change: https://github.com/Yubico/yubikey-manager/commit/7b54512a05dbb31a332babd622b8445a1f543daf#diff-017758723c502ad32603406c828aa10c

Fix 'Require Touch' ykman syntax

---

README.md

Recently a PR was merged that edited the [Require Touch](https://github.com/drduh/YubiKey-Guide#require-touch) section to update the command syntax for newer versions of `ykman`.
However, versions of `ykman` that are still being distributed widely (such as Debian's) are still too old to have `set-touch`, and still use the old `touch` syntax.
This PR adds a note so that individuals with the old versions don't have to go on a searching spree to find the right command syntax.

Leave a note that `set-touch` used to be `touch`

---

README.md

When exporting keys, using `-o` at the end will only output to the console and not the file. Using `--output` instead of `-o` says `gpg: Note: '--output' is not considered an option`. Moving `-o`/`--output` to before `--export` command seems to solve this problem.
Tested with:
gpg (GnuPG) 2.2.11 and 2.2.17
PowerShell 5.1.18362.145
Windows 10 1903 18362.267
Possibly related to #67

Move Output Option to Earlier in Export Command for Windows

---

README.md

When adding GPG SSH agent configuration to shell rc file, redirect output of gpg-connect-agent to /dev/null so that it doesn't output `OK` every time you bring up a new shell

Redirect gpg-connect-agent ouput to /dev/null when added to shell `rc` file

---

README.md

Hi, I was following guide and I stumbled upon http/404 when trying to download Debian image. Small thing, but could be updated. :)

New Debian version: 10.1.0

---

README.md

I've been hit by this for hours until I `strace`'d `pinentry` only to find out it was expecting a `$DBUS_SESSION_BUS_ADDRESS` variable.

Added a fix for failing ssh / GUI pinentry

---

README.md

Add command to instruct Git to use WinGPG. By default, Git ships its own older copy of gpg, and it will fail to authenticate with the gpg keyring setup using WinGPG unless we tell it to use the new one.

Update GitHub instructions on Windows

---

README.md

`gnupg2` has been [removed since March 2012](https://lists.archlinux.org/pipermail/arch-dev-public/2012-March/022690.html)

Fix gnupg package name for Arch

---

README.md

I started using my key and realised that the primary (default) user ID was not the first one that I added.
This change adds a step to set the primary user ID while setting up the identities.
I'm not sure whether it's possible to edit uids without going to the backup.

Add information about setting the primary user ID

---

README.md

Adds more detail about what to do with multiple YubiKeys.
I wasn't quite sure if I could reuse `$GNUPGHOME` after running `keytocard`. The answer to that is definitely no.

Add more detail about what to do with multiple YubiKeys

---

README.md

Hi,
I thought that the guide could stress more the importance of creating a revoke certificate, should the backup fail.
Unfortunately it happens that a lost or failing backup will invalidate all the work done to create a strong GPG workflow.
What do you think? Feel free to suggest improvements!
thanks for reviewing this pr

Add instructions to create a revoke certificate

---

README.md

This is specifically during setup when rotating keys. I didn't notice that `--expert` was missing and I wasn't able to create an RSA key with custom capabilities.

Include --expert when editing master key

---

README.md

While following the instructions (using the Debian live system) I noticed that the command to create the revocation file was in incorrect order and would always produce an error.
According to `man gpg` the order of arguments should be
`gpg [--homedir name] [--options file] [options] command [args]`
In this case `--gen-revoke` is the command, `$KEYID` is an argument and
`--output $GNUPGHOME/revoke.asc` is an option. Previously this was
incorrect (the command came first) and would spawn an error.

Fix order of revocation command

---

README.md

There are two anchors with the same name and this breaks navigation.

Fix broken anchor

---

README.md

- Adding information on the minimum required PIN and PUK lengths.
- Adding a suggestion to run the `gpg-agent` with debug output to the troubleshooting section.
- Adding a blocked PIN as a possible cause for the `gpg: decryption failed: secret key not available` error.
- Adding a link that was helpful in debugging the issue and which contains the source for the `gpg-agent` debug arguments.
- When attempting to set a too short PIN, the resulting error on the command line can be missed due to the UI repeating the options below it.
- Pinentry (on Fedora 32 / Gnome 3) happily stores the bogus PIN and even counts down the retry counter when entering the correct (default) one. This can be resolved by unblocking the PIN.
- When running the `gpg-agent` with debug output (a tip found in the added …

Add information on potential PIN issues and how to debug them

---

README.md

Setting the touch policy to `on` does not prevent the policy from
later being turned off again. Setting it to `fixed` is more secure
because it can not be turned off.
If someone wants to disable the touch policy they can always restore
the keys from the backups created in the guide.

Set touch policy to fixed.

---

README.md

Master key shall only be used to certify other keys. The usage indicator in
`README.md` is inconsistently shown as `SC` and `C`.

Fix usage inconsistency

---

README.md

As mentioned in #197, the previous behaviour would require users to
touch their key any time an authentication, signing, or encryption
operation was performed. In some situations, this behaviour would be
undesirable and the only way to revert it would be fully resetting the
key and starting from scratch. Rather than using `fixed`, this commit
simply turns the feature `on` so the user can change it later if they
wish.
Additionally, a note about the other policies was included so users can
decide for themselves which fits their situation better.

change defaults and add info to #Require touch

---

README.md

This will avoid having to keep the guide up to date with the latest version number.

Changes command to download Debian ISO to use the value in the SHA512SUMS file

---

README.md

if not done, in the next step you get error: 
```
gpg: keyblock resource '/home/..../gnupg-workspace/pubring.kbx': No such file or directory
gpg: no writable keyring found: Not found
```

unset GNUPGHOME variable

---

README.md

[Mutt](http://www.mutt.org/), a traditional yet powerful email client in terminal, has strong GPG support, hence may be a choice for Yubikey users when considering email.

Add Mutt email client gpg config and Some note when configuring

---

README.md

Big PR! Changes involving multiple sections, and multiple reviewers/assignees may be needed.
There are two agents when coping with ssh and gpg, namely gpg-agent and ssh-agent. GPG-Agent has a broader usage as it can emulate an ssh-agent.
Forwarding of agents is needed by many, and it is one benefit of agents as it separates the logic of one program. However, it may be confusing or even misleading for new users, especially when there are two agents. 
Unfortunately, in this README, two agents are mixed, hence **two ways of agent forwarding are mixed or only one of them is explained**. This may lead to configuration errors hence forwarding may not work.
Changes made are explained in commit messages, below is the summary of changes made.
1. Separate GPG-Agent forwarding from SSH section as a …

Add New Agent Forward Method and Clarify Two Methods

---

README.md

On macOS, a LaunchAgent needs to be created to overwrite the system's SSH agent.
see 
- https://github.com/drduh/YubiKey-Guide/issues/229
- https://evilmartians.com/chronicles/stick-with-security-yubikey-ssh-gnupg-macos
- https://jms1.net/yubikey/make-ssh-use-gpg-agent.md

Add SSH setup for macOS GUI applications

---

README.md

The current advice to use `quit` at the end of the key renewal section seems dangerously wrong: `quit` does not save any changes.
https://www.gnupg.org/gph/en/manual/r899.html

Fix: "quit" to save -> "save" to save

---

README.md

Fixes the following warning:
WARNING: The use of this command is deprecated and will be removed!
Replace with: ykman openpgp keys set-touch

Update usage of ykman

---

README.md

When using a previously provisioned YubiKey on a new computer,
I was met with an "Unusable public key" error when trying to insert
a new password, despite being able to decrypt pass entries.
I tried setting the trust on the key via `gpg --edit-key`, but was
then met with "Need secret key to do this."
I found that the solution is apparently to use the `trust-key`
directive in `~/.gnupg/gpg.conf`, which is not mentioned in the README
at the moment.

Add note about pass insert error and `trust-key` usage

---

README.md

````nixpkgs/nixos/modules/installer/cd-dvd/installation-cd-graphical-kde.nix```` no longer exists. 
Update to ````nixpkgs/nixos/modules/installer/cd-dvd/installation-cd-graphical-plasma5.nix````

Update nixos LiveCD example

---

switch-to-backup-yubikey

Some GitHub users have asked in the issues why can't I use two Yubikeys (one as a backup). It's a question often asked 
The usual answer given across the web is that you can't as GPG replaces the key with key stubs when you quit and save (if you don't save then the Yubikey appears useless as GPG doesn't delete the keys and carries on using them off the keyring.
If once you have run keytocard to transfer your keys to the Yubikey#1 you QUIT WITHOUT SAVING then you can repeat the whole process again and put in your Yubikey#2 and keytocard again. this time QUIT AND SAVE.
GPG will now replace the keys with a key stub pointing to the Yubikey with the card serial number (see Yubikey serial on back of key) when you try to decrypt/sign/authenticate. The first Yubikey will be ignored despite the …

Script to switch between two Yubikeys with identical keys

---

README.md

As detailed in their recent press release and blog post
https://www.yubico.com/blog/github-now-supports-ssh-security-keys/

added mention of ssh key support for blue security keys

---

README.md

added to section multiple Yubikeys section 
section describes the issue and the remedy for GPG stubs only pointing to the Yubikey that was last subject to the keytocard command

switching between Yubikeys

---

README.md

Trying to fix:
- drduh/YubiKey-Guide/issues/248
This is an attempt to unblock @andrewpmartinez's work on drduh/YubiKey-Guide/pull/249, and to add more details.

Clarified PIN config

---

README.md

Fixed a broken link found in
https://github.com/drduh/YubiKey-Guide/issues/287 and updated the text.

Fixed broken "Change PUK" link

---

README.md

Fixes #263. Really though decision to make whether a paper printout with the password is a good way to go (recoverable but needs a really good place to keep) or not (more protection, but possibly worthless).

Point out that paperkey backups are password-protected

---

README.md

When i was following the guide I could not fetch the gpg config because I was missing wget

Adding wget as prerequisite on macOS

---

README.md

```diff
- numnber
+ number
```
Closes drduh/YubiKey-Guide#297

Fix typo (numnber → number)

---

README.md

Since the press release was a year ago, let's replace "just released" with month and year.

State release date of Yubico press release

---

README.md

I Installed the `ykman` with `sudo apt install yubikey-manager` in a Ubuntu 20.04 and noticed that the command to change the pin retry attempts has chaged.
This PR updates the documentations with the new command

Update the command to change the pin retry attempts

---

README.md

The latest available version of OneRNG supports Python 3.
* https://github.com/OneRNG/onerng.github.io/commit/334dd2e65d9f57c9d5f983b14a480c8cfb11801d

Update OneRNG to version 3.7

---

README.md

I created this PR to create a required software section for Fedora. I believe all software is in the packages but I only use this guide for SSH with a yubikey and those packages worked for me. 
Unfortunately, you have to add the `rpmsphere-release` repository for the `secure-delete` package.

Add Fedora required software section

---

README.md

See [This ArchLinux BBS Topic](https://bbs.archlinux.org/viewtopic.php?id=274571) for more info. OpenSSH 8.9p1 and OpenSSH 9
appear to break Yubikey client authentication.

Possible fix for the 'signing failed: agent refused operation' error

---

README.md

This PR adds `piv-agent` to the list of alternatives. It provides another way to use a Yubikey with `gpg` and `ssh` backed by the PIV applet instead of the OpenPGP applet.

chore: add piv-agent to Alternatives section

---

README.md
contrib/gen-params-ed25519
contrib/gen-params-rsa4096

This patchset rewrites the tutorial to create the master and the sub keys and creates a `./contrib` directory with two templates (RSA4096 and ED25519) to create the master key.
I've tried to be careful and keep consistent all references to paths and keyids, but please double check and proof-read (a small typo on a KEYID could be really confusing for readers).
[Rendered version](https://github.com/apiraino/YubiKey-Guide/blob/rewrite-key-creation-take2/README.md).
Thanks for reviewing this PR.
Closes #244 
Related to #105

Rewrite key creation

---

README.md

Primarily, the goal of this change is to create an air-gapped environment, i.e. one with networking completely disabled.
To make this work, I had to bake the guide into the image itself, along with the GPG config, and contrib files.
I took some inspiration from @dhess https://github.com/dhess/nixos-yubikey, then simplified it a little after that.
While I was at it, I found a way to set the pinentry nicely depending on the desktop environment that the config ends up being used for, and also solves https://github.com/drduh/YubiKey-Guide/issues/278.
And I made it easy to choose a different installation image. One can choose from Plasma5, Gnome, or a CLI-only installer. I tested all 3 of these and it works for me, though the Gnome version seemed to freeze once the Gnome shell loads in …

Air-gapped NixOS LiveCD image

---

README.md

If I try to delete the directory and then issue the `gpg --delete-secret-key $KEYID` command gpg gets very confused
```
gpg: keyblock resource '/var/folders/5d/wdpp...<blah>...000gn/T/gnupg_blah/pubring.kbx': No such file or directory
gpg: key "0x690...<blah>...ABF01" not found: Not found
gpg: 0x690...<blah>...ABF01: delete key failed: Not found
```

Reorder cleanup commands

---

README.md

With the release of YubiKey Manager 5.1.0, the command for setting touch requirement for encryption is now `dec` instead of `enc`. [The latter is now only an alias and will be removed in ykman 6](https://github.com/Yubico/yubikey-manager/blob/4abe6b5573119488feb5f8db03f880f08836fed1/ykman/_cli/openpgp.py#LL54C18-L54C18)

Update ykman set-touch instructions

---

README.md

Trying to use `yubioath-desktop` results on this error:
```console
yubioath-desktop has been deprecated by upstream in favor of yubioath-flutter
```
On the current stable channel (23.05).

Required Software/NixOS: Replace yubioath-desktop with yubioath-flutter

---

README.md

This just updates the rpmsphere version to the latest; the current link is dead. In the long run, a way to automatically get the latest version would probably be a better idea, though.

Update rpmsphere version

---

README.md

I wrote a quick tool that could be useful to others called `makegpg`. I wonder if you'd like to link to it? Many things are missing relative to your guide, but one addition is a backup / export system that also puts recovery scripts next to the backed-up keys and tests the keys as they are generated. Happy to license this tool in a compatible way and accept improvements from you and your users.
From its README:
```
This tool creates and maintains a GPG keyring with a private key according to DrDuh's guide:
https://github.com/drduh/YubiKey-Guide
Initially, this repository is used to generate a set of keys. Once this set of keys are
generated, this repository contains secrets that should be kept offline. In operation,
this repository is used to renew (sub-)keys, make backups, and perform …
```

Add link to "makegpg" tool

---

README.md

It's explained in the text, but there's no example.

fix: add an explicit example about publishing the pubkey when expiring

---

README.md

Added a note on installing `hopenpgp-tools` as it isn't included in the stable Debian 12 repositories or the backports, but it is available in the sid.
On the other hand, `yubikey-manager` is available in the stable repository and, on Debian 12, installing `python3-pip`, `python3-pyscard` and `pip install PyOpenSSL` is not necessary, so I also added a note on that.
related to https://github.com/drduh/YubiKey-Guide/issues/389

add notes for installing #Required Software on Debian 12

---

README.md
flake.lock
flake.nix

Now `nixpkgs` will be pointing to a specific release, which has a much smaller chance to unexpectedly break. Currently 23.11. The next one will be 24.05, 24.11, etc.
NixOS *releases* receive security updates, but packages are upgraded conservatively, thus don't generally break. As a result, we should need to worry about NixOS upgrades every 6-12 months. The upgrade means "bump the version number and try to build it". If it breaks, it will generally break only then. Less reactive, more proactive surprises.
`flake.nix` was written by @thomaseizinger in
https://github.com/drduh/YubiKey-Guide/issues/406. Changes from the
original:
- change Gnome to xfce. Now it loads with 384MB of RAM and works well with the simplest graphics (hello qemu).
- less nasty workaround for hopenpgp-tools. Fixed …

NixOS Live Image: convert to a flake

---

README.md

Quote ISO URL, and add `$` RegExp end-of-string anchor to return only the ISO file and none of the other entries that contain `xfce.iso`.
This avoids unnecessary cURL errors.

Quote Debian Live ISO URL, and add $ to AWK RegExp.

---

README.md

Issue #404 reports "GPG acts like my YubiKey isn't plugged in".
With GnuPG 2.3 and later, the system can get into a loop where it prompts for insertion of a YubiKey even though that YubiKey is already connected.
The solution for this is to set `disable-ccid` in `~/.gnupg/scdaemon.conf`.
Testing suggests setting `disable-ccid` does not interfere with earlier versions of GnuPG (eg 2.2.27 on Debian Bullseye or 2.2.40 on Debian Bookworm).
This problem has also been mentioned in #277 and #256. Including a step in the Guide to set `disable-ccid` may help minimise recurrence.
Also takes the opportunity to ensure `~/.gnupg` directory exists on a new system before downloading `gpg.conf`.
References:
* Ludovic Rousseau
- [GnuPG and PC/SC conflicts](https://ludovicrousseau.blogspot.com/2019/06/gnupg- …

add step to set `disable-ccid` in `scdaemon.conf`

---

README.md

Unclear what benefit this has. The Entropy section would benefit from expert review.
fix #394

remove yubikey as rng

---

README.md

`gpg --quick-add-key` seems to be only accepting fingerprints and rejecting key ID-s:
```
$ export KEYID=0x450944965A788EE4
$ gpg --quick-add-key "$KEYID" rsa4096 auth 2y
gpg: "0x450944965A788EE4" is not a fingerprint
```
so we should extract the fingerprint from the following:
```
$ gpg --fingerprint $KEYID
pub   rsa4096/0x450944965A788EE4 2024-03-04 [C]
Key fingerprint = 6768 2AB6 06DF 7C9A 8BB6  C2D6 4509 4496 5A78 8EE4
uid                   [ultimate] Test User <test@example.com>
```
...and the most format-agnostic grep pattern I could think of was to find the first occurrence of groups of hexadecimal numbers and spaces, and then truncate the result.

update gpg --quick-add-key commands

---

README.md

Move Improve entropy and Enable KDF instructions to a later, optional hardening section. The benefit of these steps is not immediately obvious and they probably do not need to be the default process for most users.
More validation and passphrase instructions.

Optional hardening section, additional validation steps

---

flake.nix

Currently, the `icon` of the YubiKey Guide icon points to an inexistent file.
Changes made in this PR fix this path by pointing to the `png` file with the highest resolution available.

Fix Guide Desktop Icon

---

flake.nix

Currently, the screensaver is enabled. This causes the session to lock after a certain amount of time.
With autologin enabled and the user having no default password, this means that the session cannot be unlocked again.
Thus, changes made in this PR disable the screensaver.

Disable Screensaver

---

flake.nix

Currently, when trying to open the guide, the corresponding markdown file is opened using Xfce's [Mousepad](https://docs.xfce.org/apps/mousepad/start) app which looks a little janky (considering it doesn't use a monospace font and doesn't do any syntax highlighting).
Changes made in this PR add `okular` to the NixOS image which is automatically associated to `text/markdown` files, effectively causing markdown files to be opened using `okular` by default.

Add a Markdown Viewer to the NixOS Image

---

diceware-vt.patch
flake.nix

Although, the `diceware` CLI is included in the NixOS image, passphrases generated with it are slightly different from the page linked in the guide (https://secure.research.vt.edu/diceware/).
Changes made in this PR add the `grempe/diceware` project to the NixOS image and also patch it with the minor changes published on the `https://secure.research.vt.edu/diceware/` website to generate slightly different-looking passphrases (including numbers and symbols).

Add the `diceware` Web-App to the NixOS ISO

---

README.md

This PR addresses issue #434.
When merely setting the `GNUPGHOME` variable without exporting it, subsequent `gpg` calls will silently ignore this variable and instead use `~/.gnupg` as home.
Changes made in this PR add the `export` command to the guide for preventing readers (such as myself)  to do the same error.
That's about everything I wanted to PR-spam!
Thank you so much for your great work, this really helps me a lot 😄

Suggest Exporting the `GNUPGHOME` Variable in the Guide

---

README.md

This adds a section for network considerations and guidance on disabling unnecessary services that may be bound to all interfaces (and in some cases are listening by default). While the risk is relatively low here, it's always a good idea to disable services that aren't needed or in use.
I've frequently repeated these steps / checks when, for example, running a live OS to download and update firmware over a flat or untrusted network. I didn't see any direct mentions to this in the issues or past pull requests, but it seemed like it could fit with the rest of the guide.

Add networking section to README.md

---

flake.lock
flake.nix

- remove hopenpgp-tools (as per README)
- add dirmgr
- add rng-tools
- update ref to `github:drduh/config` (via `nix flake update --commit-lock-file`).

NixOS: bump to 24.05

---

flake.lock
flake.nix

Hi, I've updated flake.lock as per the README.md in this repository. I've noticed that the `stateVersion` variable was still set to 23.11. I suppose this is safe to change, since I don't expect anyone update their yubikey live usb.
While testing out the build, I've also noticed that a setting path was renamed (`autoLogin`), and I have adjusted the path accordingly.

Update flake.lock, system.stateVersion and migrate displayManager setting

---

README.md

- add instructions to configure the thunderbird client with this setup
- add warning for commonly encountered issues when decrypting emails (Resolves #448)

mail/thunderbird: add instructions & warnings

---

README.md

Hi,
Thanks for the guide. It's very informative.
I would like to suggest a change to pass the passphrase to gpg from stdin via the --passphrase-fd 0 option instead of via the --passphrase option. The latter exposes the passphrase to observation by other processes on the system and the gpg man page includes a disclaimer for it: "Don't use this option if you can avoid it". Although I acknowledge that the README recommends a single user, ephemeral Debian Live environment, thus reducing the risk of exposing the passphrase as an argument, users may choose to ignore that recommendation so it seems best to protect them from themselves where possible. It's potentially also arguable that some users may naively take the current command and use it in other, more risky scenarios, not realizing the …

Pass passphrase to gpg using --passphrase-fd 0

---

README.md

Hi drduh,
Please consider this proposal to address [Missing section for adding uids](https://github.com/drduh/YubiKey-Guide/issues/445).
Debian Live version tested:
```
009f482430b8505bba8099aeac3f59eab92ddfa30ae8910d6293f7e198194bad24fa625fcfa38813e6e25b2b7502a542fa04af4e4c2a52376c36162fea8debf7  debian-live-12.8.0-amd64-gnome.iso
user@debian:~$ cat /etc/os-release                                                                                                                                                                                                                                                                                                                       
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)" …
```

Addresses issue 445

---

README.md

I recently moved away from the archived weasel-pageant and some other hacky options. I found that usbipd-win is a very nice solution. I ran into authentication issues on my PC so I included those in the docs. I am not sure if you want to include this in the README. Feel free to reject or change this PR. Just thought I would contribute back since this documentation helped me.  
PS: I set this up a while ago, but I believe all I had to do was setup usbipd-win according to their docs and then add the polkit rules, but maybe someone could verify.

docs(wsl): Add usbipd-win in WSL setup

---

README.md

echo from GNU coreutils requires -e to interpret backslash escape sequences
without this, the encrypted file contains `\ntest message`

ensure newline is expanded

---

README.md

Updated instructions for commit signing include:
- Using a SSH key for signing
- Snippet demonstrating configuring the Git user identity
- Enabling commit and tag signing by default
Source:
- https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key

Update instructions for commit signing

---

config/gpg-agent.conf

Adjusts the `gpg-agent.conf` template as follows:
1. Adds more `pinentry-program` variants likely to be found on current Linux and macOS systems.
2. Groups entries by OS and package.
3. Makes all `pinentry-program` directives inactive (commented-out).
At present, the `pinentry-program` directive active by default is:
```
pinentry-program /usr/bin/pinentry-curses
```
This works on Linux but fails on macOS.
However, if `gpg-agent.conf` either does not exist, or exists but does not contain **any** active `pinentry-program` directives, then my experimentation shows current OS releases behave as follows:
* Linux invokes:
- `/usr/bin/pinentry-gnome3` (if a Desktop environment is available)
- `/usr/bin/pinentry-curses` (otherwise)
I have tested Debian, Ubuntu and Raspberry Pi OS.
* macOS …

2025-06-18 gpg-agent.conf better default pinentry-program behaviour

---

README.md

that's the equivalent of the MacPorts command to the "Using YubiKey" section.

fix: add missing macOS `brew` command

---

README.md

Use `gpg --edit-card` instead of `gpg-card` command.
fixes #513

fix: use working command to get GPG public key
